import machine
import time

gsm = machine.UART(2,115200)
gsm.write('ATI\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+CGMR\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+CBC\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+COPS=?\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+COPS?\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+CSQ\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+CREG\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=3,1,"APN","vivo.com.br"\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=3,1,"USER","vivo"\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=3,1,"PWD","vivo"\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=3,1,"Contype","GPRS"\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=1,1\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SAPBR=2,1\r')
time.sleep(1)
print(gsm.read())

# while True:
gsm.write('AT+EMAILCID=1\r')
time.sleep(1.5)
print(gsm.read())
gsm.write('AT+EMAILTO=30\r')
time.sleep(1.5)
print(gsm.read())
gsm.write('AT+SMTPSRV="smtp.gmail.com,465"\r')
time.sleep(2)
print(gsm.read())
gsm.write('AT+SMTPAUTH=1,"datalogger.simcosta@gmail.com","SiMCost4"\r')
time.sleep(2)
print(gsm.read())
gsm.write('AT+SMTPFROM="datalogger.simcosta@gmail.com"\r')
time.sleep(2)
print(gsm.read())
gsm.write('AT+SMTPRCPT=1,0,"mariana.obiedo@gmail.com"\r')
time.sleep(2)
print(gsm.read())
gsm.write('AT+SMTPSUB="teste"\r')
time.sleep(1)
print(gsm.read())
gsm.write('AT+SMTPBODY>"epa, esse eh um teste"\r')

gsm.write('AT+SMTPSEND\r')
time.sleep(2)
print(gsm.read())



